INSERT INTO [dbo].[Product] ([Name],[Price]) VALUES (N'Vienna Sausage',14,1)
INSERT INTO [dbo].[Product] ([Name],[Price]) VALUES (N'Princess Diana Beanie Baby',200000,1)
INSERT INTO [dbo].[Product] ([Name],[Price]) VALUES (N'A Somewhat Used Tire',53,2)
INSERT INTO [dbo].[Product] ([Name],[Price]) VALUES (N'Sound Machine',72,2)
INSERT INTO [dbo].[Product] ([Name],[Price]) VALUES (N'Alexs Soul',14000000,3)
INSERT INTO [dbo].[Product] ([Name],[Price]) VALUES (N'Frozen Super Size Fries',4,3)
INSERT INTO [dbo].[Product] ([Name],[Price]) VALUES (N'Lava Lamp',12,4)
INSERT INTO [dbo].[Product] ([Name],[Price]) VALUES (N'Inflatable Unicorn Hat',6,4)
INSERT INTO [dbo].[Product] ([Name],[Price]) VALUES (N'Everlasting Dry Erase Markers',204,5)
INSERT INTO [dbo].[Product] ([Name],[Price]) VALUES (N'Adams MacBook',100,5)

